name = "vera-router"
main = "src/index.ts"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]

# routes = [{ pattern = "router.vera.ai", custom_domain = true }]

[[kv_namespaces]]
binding = "ROUTING_TABLE"
id = "<KV_NAMESPACE_ID>"
preview_id = "<KV_PREVIEW_NAMESPACE_ID>"
