name = "army-router"
account_id = "eb4ad8fa494badb4359e91aa85ebf768"
main = "src/index.ts"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]

# routes = [{ pattern = "router.army.ai", custom_domain = true }]

[[kv_namespaces]]
binding = "ROUTING_TABLE"
id = "aa0a6fbff64147bc95814a4491cb1725"
preview_id = "b89b8349fe6646689993a8044be48966"
