/**
 * Generate the OG image (1200x630) for the website.
 *
 * Simple design: dark background, centered parrot mark, "Vera" wordmark, URL.
 * Uses sharp only — no canvas, no font installs. Text is rendered via SVG and
 * picks up the OS sans-serif font at rasterization time.
 *
 * Other icons (favicon, apple-touch, android, etc.) are already in place and
 * are not regenerated by this script.
 */
import sharp from "sharp";
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, "..", "website", "public");

const W = 1200;
const H = 630;

const BG = "#0a0a0f";
const TEXT = "#f0f0f5";
const MUTED = "#8888a0";

// The parrot icon PNG has a solid white background. Strip it so the mark sits
// cleanly on the dark OG canvas. Cheap chroma key: any pixel that is near-white
// becomes transparent, with a soft rolloff for anti-aliased edges.
async function loadLogoTransparent(path, size) {
  const { data, info } = await sharp(path)
    .resize(size, size)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  for (let i = 0; i < data.length; i += 4) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const lum = Math.min(r, g, b);
    if (lum >= 250) {
      data[i + 3] = 0;
    } else if (lum >= 220) {
      // soft rolloff: fade alpha as luminance approaches white
      data[i + 3] = Math.round(((250 - lum) / 30) * 255);
    }
  }

  return sharp(data, {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();
}

async function generateOGImage() {
  // Source logo — 192x192 parrot mark already in public/
  const logoBuf = await loadLogoTransparent(join(publicDir, "icon-192.png"), 180);

  const textSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
    <style>
      .title { font: 700 132px -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; fill: ${TEXT}; letter-spacing: -4px; }
      .url   { font: 500 28px  -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; fill: ${MUTED}; letter-spacing: 0.5px; }
    </style>
    <text x="600" y="445" text-anchor="middle" class="title">Vera</text>
    <text x="600" y="555" text-anchor="middle" class="url">agent-vera.com</text>
  </svg>`;

  const bg = sharp({
    create: { width: W, height: H, channels: 4, background: BG },
  });

  return bg
    .composite([
      { input: logoBuf, top: 110, left: (W - 180) / 2 },
      { input: Buffer.from(textSvg), top: 0, left: 0 },
    ])
    .png()
    .toBuffer();
}

async function main() {
  console.log("Generating OG image (1200x630)...");
  writeFileSync(join(publicDir, "og-image.png"), await generateOGImage());
  console.log("  ✓ og-image.png");
  console.log("\nDone!");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
