/**
 * Generate the OG image (1200x630) for the website.
 *
 * Simple design: cream background, centered parrot mark, "Vera" wordmark, URL.
 * Satoshi is the brand font — we load the TTFs from scripts/fonts/satoshi via
 * opentype.js and convert text to SVG paths, then rasterize with sharp. This
 * sidesteps fontconfig entirely, which sharp's bundled librsvg on macOS does
 * not reliably consult.
 *
 * Other icons (favicon, apple-touch, android, etc.) are already in place and
 * are not regenerated by this script.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";
import sharp from "sharp";

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, "..", "website", "public");
const fontsDir = join(__dirname, "fonts", "satoshi");

const W = 1200;
const H = 630;

// Match the website theme (see website/src/layouts/Layout.astro :root)
const BG = "#f0ede8";
const TEXT = "#0d2818";

// The parrot icon PNG has a solid white background. Strip it so the mark sits
// cleanly on the cream OG canvas. Cheap chroma key: any pixel that is near-white
// becomes transparent, with a soft rolloff for anti-aliased edges.
async function loadLogoTransparent(path, size) {
  const { data, info } = await sharp(path)
    .resize(size, size)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  for (let i = 0; i < data.length; i += 4) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const lum = Math.min(r, g, b);
    if (lum >= 250) {
      data[i + 3] = 0;
    } else if (lum >= 220) {
      // soft rolloff: fade alpha as luminance approaches white
      data[i + 3] = Math.round(((250 - lum) / 30) * 255);
    }
  }

  return sharp(data, {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();
}

// Convert a string to an SVG <path> using the given TTF. Returns the path data
// plus the measured bounding box so callers can center/position it.
function textToPath(font, text, { size, x, y, fill, fillOpacity = 1 }) {
  const path = font.getPath(text, x, y, size);
  const bbox = path.getBoundingBox();
  const d = path.toPathData(3);
  const opacityAttr = fillOpacity < 1 ? ` fill-opacity="${fillOpacity}"` : "";
  return {
    svg: `<path d="${d}" fill="${fill}"${opacityAttr} />`,
    bbox,
    width: bbox.x2 - bbox.x1,
  };
}

// Render `text` centered horizontally around `cx`, with its baseline at `y`.
function centeredText(font, text, { size, cx, y, fill, fillOpacity }) {
  // First measure at origin so we can offset to the true center.
  const measured = textToPath(font, text, { size, x: 0, y: 0, fill, fillOpacity });
  const offset = measured.bbox.x1 + measured.width / 2;
  return textToPath(font, text, {
    size,
    x: cx - offset,
    y,
    fill,
    fillOpacity,
  });
}

async function generateOGImage() {
  const titleFont = await opentype.load(join(fontsDir, "Satoshi-Black.ttf"));
  const bodyFont = await opentype.load(join(fontsDir, "Satoshi-Medium.ttf"));

  const logoBuf = await loadLogoTransparent(join(publicDir, "icon-192.png"), 180);

  const title = centeredText(titleFont, "Vera", {
    size: 140,
    cx: W / 2,
    y: 445,
    fill: TEXT,
  });
  const url = centeredText(bodyFont, "agent-vera.com", {
    size: 28,
    cx: W / 2,
    y: 555,
    fill: TEXT,
    fillOpacity: 0.55,
  });

  const textSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
    ${title.svg}
    ${url.svg}
  </svg>`;

  const bg = sharp({
    create: { width: W, height: H, channels: 4, background: BG },
  });

  return bg
    .composite([
      { input: logoBuf, top: 110, left: (W - 180) / 2 },
      { input: Buffer.from(textSvg), top: 0, left: 0 },
    ])
    .png()
    .toBuffer();
}

async function main() {
  console.log("Generating OG image (1200x630)...");
  writeFileSync(join(publicDir, "og-image.png"), await generateOGImage());
  console.log("  ✓ og-image.png");
  console.log("\nDone!");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
