name = "army-control-plane"
account_id = "eb4ad8fa494badb4359e91aa85ebf768"
main = "src/index.ts"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]

# routes = [{ pattern = "api.army.ai", custom_domain = true }]

[[kv_namespaces]]
binding = "ROUTING_TABLE"
id = "aa0a6fbff64147bc95814a4491cb1725"
preview_id = "b89b8349fe6646689993a8044be48966"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "bb010975d56049d28fb61a1b3d627950"
preview_id = "1dea428553cf47e181da9ac16ce1351f"

[[hyperdrive]]
binding = "DB"
id = "3ef1724bda9a4da1b96d080e65d8b0b2"

[vars]
FLY_APP = "pi-agent-images"
BASE_URL = "https://army-control-plane.stepandel.workers.dev"
GITHUB_APP_SLUG = "agent-vera"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
